/*****************************************************************************
Scripts to use for the use case exercise. 

assumptions:

postgresql installed
foreign data wrapper installed

staging tables where the data lands:

json_tmp (foreign table)
explore_set (staging table)

tables that tableau will use:

explore_brand
explore_mentions
explore_hashtags
explore_links
***************************************************************************/


/***************************************************************************
If you have not created the extension and server for postgres already, 
please do so now.  You will only need to run this once.
****************************************************************************/

CREATE EXTENSION json_fdw;
CREATE SERVER json_server FOREIGN DATA WRAPPER json_fdw;

/**********************************
Create the foreign and physical
tables
**********************************/
DROP FOREIGN TABLE IF EXISTS json_tmp;
CREATE FOREIGN TABLE json_tmp
(
"demographic.gender" TEXT,
"facebook.application" TEXT,
"facebook.author.avatar" TEXT,
"facebook.author.id" TEXT,
"facebook.author.link" TEXT,
"facebook.author.name" TEXT,
"facebook.caption" TEXT,
"facebook.created_at" DATE,
"facebook.description"	TEXT,
"facebook.icon"	TEXT,
"facebook.id" TEXT,
"facebook.likes.count" INT,
"facebook.likes.ids" TEXT [],
"facebook.likes.names" TEXT [],
"facebook.link"	TEXT,
"facebook.message" TEXT,
"facebook.name"	TEXT,
"facebook.og.app" TEXT,
"facebook.og.by" TEXT,
"facebook.og.length" TEXT,
"facebook.og.page" TEXT,
"facebook.og.photos" TEXT,
"facebook.picture" TEXT,
"facebook.place.id" TEXT,
"facebook.place.location.city" TEXT,
"facebook.place.location.country" TEXT,
"facebook.place.location.latitude" FLOAT,
"facebook.place.location.longitude" FLOAT,
"facebook.place.location.state" TEXT,
"facebook.place.location.street" TEXT,
"facebook.place.location.zip" TEXT,
"facebook.place.name" TEXT,
"facebook.source" TEXT,
"facebook.story" TEXT,
"facebook.story_tags.id" TEXT,
"facebook.story_tags.length" TEXT,
"facebook.story_tags.name" TEXT,
"facebook.story_tags.offset" TEXT,
"facebook.story_tags.type" TEXT,
"facebook.to.ids" TEXT [],
"facebook.to.names" TEXT [],
"facebook.type"	TEXT,
"interaction.author.avatar" TEXT,
"interaction.author.contributions" TEXT,
"interaction.author.friends_count" TEXT,
"interaction.author.hash_id" TEXT,
"interaction.author.id" BIGINT,
"interaction.author.link" TEXT,
"interaction.author.name" TEXT,
"interaction.author.talk" TEXT,
"interaction.author.url" TEXT,
"interaction.author.username" TEXT,
"interaction.content" TEXT,
"interaction.contenttype" TEXT,
"interaction.created_at" DATE,
"interaction.geo.latitude" FLOAT,
"interaction.geo.longitude" FLOAT,
"interaction.hashtags" TEXT[],
"interaction.id" TEXT,
"interaction.link" TEXT,
"interaction.mentions" TEXT[],
"interaction.schema.version" INT,
"interaction.source" TEXT,
"interaction.tags" TEXT[],
"interaction.title" TEXT,
"interaction.type" TEXT,
"interaction.subtype" TEXT,
"klout.score" INT,
"klout.topics" TEXT[],
"language.tag" TEXT,
"language.tag_extended" TEXT,
"language.confidence" INT,
"links.code" INT[],
"links.created_at" TEXT[],
"links.domain" TEXT[],
"links.meta.charset" TEXT[],
"links.meta.content_type" TEXT[],
"links.meta.description" TEXT[],
"links.meta.keywords" TEXT [],
"links.meta.lang" TEXT[],
"links.meta.opengraph.author" TEXT,
"links.meta.opengraph.city" TEXT,
"links.meta.opengraph.country" TEXT,
"links.meta.opengraph.director" TEXT,
"links.meta.opengraph.email" TEXT,
"links.meta.opengraph.fax_number" TEXT,
"links.meta.opengraph.image" TEXT,
"links.meta.opengraph.locality" TEXT,
"links.meta.opengraph.phone_number" TEXT,
"links.meta.opengraph.region" TEXT,
"links.meta.opengraph.site_name" TEXT,
"links.meta.opengraph.title" TEXT,
"links.meta.opengraph.type" TEXT,
"links.meta.standout" TEXT[],
"links.meta.twitter.card" TEXT,
"links.meta.twitter.description" TEXT,
"links.meta.twitter.creator" TEXT,
"links.meta.twitter.creator_id" TEXT,
"links.meta.twitter.image" TEXT,
"links.meta.twitter.image_height" TEXT,
"links.meta.twitter.image_width" TEXT,
"links.meta.twitter.player" TEXT,
"links.meta.twitter.player_height" TEXT,
"links.meta.twitter.player_stream" TEXT,
"links.meta.twitter.player_stream_content_type" TEXT,
"links.meta.twitter.player_width" TEXT,
"links.meta.twitter.site" TEXT,
"links.meta.twitter.site_id" TEXT,
"links.meta.twitter.title" TEXT,
"links.meta.twitter.url" TEXT,
"links.normalized_url" TEXT[],
"links.retweet_count" INT[],
"links.title" TEXT[],
"links.url" TEXT[],
"salience.content.entities.name" TEXT,
"salience.content.entities.type" TEXT,
"salience.content.entities.label" TEXT,
"salience.content.entities.sentiment" INT,
"salience.content.entities.evidence" INT,
"salience.content.entities.confident" INT,
"salience.content.entities.about" INT,
"salience.content.entities.themes" TEXT[],
"salience.content.sentiment" BIGINT,
"salience.content.topics.name" TEXT,
"salience.content.topics.hits" INT,
"salience.content.topics.score" FLOAT,
"salience.title.entities.name" TEXT,
"salience.title.entities.type" TEXT,
"salience.title.entities.label" TEXT,
"salience.title.entities.sentiment" INT,
"salience.title.entities.evidence" INT,
"salience.title.entities.confident" INT,
"salience.title.entities.about" INT,
"salience.title.entities.themes" TEXT[],
"salience.title.sentiment" BIGINT,
"salience.title.topics.name" TEXT,
"salience.title.topics.hits" INT,
"salience.title.topics.score" FLOAT,
"twitter.created_at" TEXT,
"twitter.domains" TEXT[],
"twitter.geo.latitude" FLOAT,
"twitter.geo.longitude" FLOAT,
"twitter.hashtags" TEXT[],
"twitter.id" TEXT,
"twitter.in_reply_to_screen_name" TEXT,
"twitter.in_reply_to_status_id" TEXT,
"twitter.in_reply_to_user_id" TEXT,
"twitter.links" TEXT[],
"twitter.media.display_url" TEXT,
"twitter.media.expanded_url" TEXT,
"twitter.media.id" INT,
"twitter.media.id_str" TEXT,
"twitter.media.media_url" TEXT,
"twitter.media.media_url_https" TEXT,
"twitter.media.source_status_id" INT,
"twitter.media.source_status_id_str" TEXT,
"twitter.media.type" TEXT,
"twitter.media.url" TEXT,
"twitter.mention_ids" BIGINT[],
"twitter.mentions" TEXT[],
"twitter.place.attributes.locality" TEXT,
"twitter.place.attributes.region" TEXT,
"twitter.place.attributes.street_address" TEXT,
"twitter.place.country" TEXT,
"twitter.place.country_code" TEXT,
"twitter.place.full_name" TEXT,
"twitter.place.id" TEXT,
"twitter.place.name" TEXT,
"twitter.place.place_type" TEXT,
"twitter.place.url" TEXT,
"twitter.retweet.count" INT,
"twitter.retweet.created_at" TEXT,
"twitter.retweet.domains" TEXT[],
"twitter.retweet.hashtags" TEXT[],
"twitter.retweet.id" TEXT,
"twitter.retweet.links" TEXT[],
"twitter.retweet.media.display_url" TEXT,
"twitter.retweet.media.expanded_url" TEXT,
"twitter.retweet.media.id" INT,
"twitter.retweet.media.id_str" TEXT,
"twitter.retweet.media.media_url" TEXT,
"twitter.retweet.media.media_url_https" TEXT,
"twitter.retweet.media.source_status_id" INT,
"twitter.retweet.media.source_status_id_str" TEXT,
"twitter.retweet.media.type" TEXT,
"twitter.retweet.media.url" TEXT,
"twitter.retweet.mention_ids" BIGINT[],
"twitter.retweet.mentions" TEXT[],
"twitter.retweet.place.country" TEXT,
"twitter.retweet.place.country_code" TEXT,
"twitter.retweet.place.full_name" TEXT,
"twitter.retweet.place.id" TEXT,
"twitter.retweet.place.name" TEXT,
"twitter.retweet.place.place_type" TEXT,
"twitter.retweet.place.url" TEXT,
"twitter.retweet.source" TEXT,
"twitter.retweet.text" TEXT,
"twitter.retweet.user.created_at" TEXT,
"twitter.retweet.user.description" TEXT,
"twitter.retweet.favourites_count" INT,
"twitter.retweet.user.followers_count" INT,
"twitter.retweet.user.friends_count" INT,
"twitter.retweet.user.geo_enabled" BOOLEAN,
"twitter.retweet.user.hash_id" TEXT,
"twitter.retweet.user.id" BIGINT,
"twitter.retweet.user.id_str" TEXT,
"twitter.retweet.user.lang" TEXT,
"twitter.retweet.user.listed_count" INT,
"twitter.retweet.user.location" TEXT,
"twitter.retweet.user.name" TEXT,
"twitter.retweet.user.profile_image_url" TEXT,
"twitter.retweet.user.screen_name" TEXT,
"twitter.retweet.user.statuses_count" INT,
"twitter.retweet.user.time_zone" TEXT,
"twitter.retweet.user.url" TEXT,
"twitter.retweet.user.utc_offset" INT,
"twitter.retweet.user.verified" BOOLEAN,
"twitter.retweeted.created_at" TEXT,
"twitter.retweeted.geo.latitude" FLOAT,
"twitter.retweeted.geo.longitude" FLOAT,
"twitter.retweeted.id" TEXT,
"twitter.retweeted.place.attributes.locality" TEXT,
"twitter.retweeted.place.attributes.region" TEXT,
"twitter.retweeted.place.attributes.street_address" TEXT,
"twitter.retweeted.place.country" TEXT,
"twitter.retweeted.place.country_code" TEXT,
"twitter.retweeted.place.full_name" TEXT,
"twitter.retweeted.place.id" TEXT,
"twitter.retweeted.place.name" TEXT,
"twitter.retweeted.place.place_type" TEXT,
"twitter.retweeted.place.url" TEXT,
"twitter.retweeted.source" TEXT,
"twitter.retweeted.user.created_at" TEXT,
"twitter.retweeted.user.description" TEXT,
"twitter.retweeted.favourites_count" INT,
"twitter.retweeted.user.followers_count" INT,
"twitter.retweeted.user.friends_count" INT,
"twitter.retweeted.user.geo_enabled" BOOLEAN,
"twitter.retweeted.user.hash_id" TEXT,
"twitter.retweeted.user.id" BIGINT,
"twitter.retweeted.user.id_str" TEXT,
"twitter.retweeted.user.lang" TEXT,
"twitter.retweeted.user.listed_count" INT,
"twitter.retweeted.user.location" TEXT,
"twitter.retweeted.user.name" TEXT,
"twitter.retweeted.user.profile_image_url" TEXT,
"twitter.retweeted.user.screen_name" TEXT,
"twitter.retweeted.user.statuses_count" INT,
"twitter.retweeted.user.time_zone" TEXT,
"twitter.retweeted.user.url" TEXT,
"twitter.retweeted.user.utc_offset" INT,
"twitter.retweeted.user.verified" BOOLEAN,
"twitter.source" TEXT,
"twitter.status" TEXT,
"twitter.text" TEXT,
"twitter.user.created_at" TEXT,
"twitter.user.description" TEXT,
"twitter.user.favourites_count" INT,
"twitter.user.followers_count" INT,
"twitter.user.friends_count" INT,
"twitter.user.geo_enabled" BOOLEAN,
"twitter.user.hash_id" TEXT,
"twitter.user.id" BIGINT,
"twitter.user.id_str" TEXT,
"twitter.user.lang" TEXT,
"twitter.user.listed_count" INT,
"twitter.user.location" TEXT,
"twitter.user.name" TEXT,
"twitter.user.profile_image_url" TEXT,
"twitter.user.screen_name" TEXT,
"twitter.user.statuses_count" INT,
"twitter.user.time_zone" TEXT,
"twitter.user.url" TEXT,
"twitter.user.utc_offset" INT,
"twitter.user.verified" BOOLEAN,
"interaction.tag_tree.BRAND" TEXT []
 )
SERVER json_server
OPTIONS (filename '/tmp/Taco.json');


/*create the physical table*/

DROP TABLE IF EXISTS explore_set;
CREATE TABLE explore_set
(	
"demographic.gender" TEXT,
"facebook.application" TEXT,
"facebook.author.avatar" TEXT,
"facebook.author.id" TEXT,
"facebook.author.link" TEXT,
"facebook.author.name" TEXT,
"facebook.caption" TEXT,
"facebook.created_at" DATE,
"facebook.description"	TEXT,
"facebook.icon"	TEXT,
"facebook.id" TEXT,
"facebook.likes.count" INT,
"facebook.likes.ids" TEXT [],
"facebook.likes.names" TEXT [],
"facebook.link"	TEXT,
"facebook.message" TEXT,
"facebook.name"	TEXT,
"facebook.og.app" TEXT,
"facebook.og.by" TEXT,
"facebook.og.length" TEXT,
"facebook.og.page" TEXT,
"facebook.og.photos" TEXT,
"facebook.picture" TEXT,
"facebook.place.id" TEXT,
"facebook.place.location.city" TEXT,
"facebook.place.location.country" TEXT,
"facebook.place.location.latitude" FLOAT,
"facebook.place.location.longitude" FLOAT,
"facebook.place.location.state" TEXT,
"facebook.place.location.street" TEXT,
"facebook.place.location.zip" TEXT,
"facebook.place.name" TEXT,
"facebook.source" TEXT,
"facebook.story" TEXT,
"facebook.story_tags.id" TEXT,
"facebook.story_tags.length" TEXT,
"facebook.story_tags.name" TEXT,
"facebook.story_tags.offset" TEXT,
"facebook.story_tags.type" TEXT,
"facebook.to.ids" TEXT [],
"facebook.to.names" TEXT [],
"facebook.type"	TEXT,
"interaction.author.avatar" TEXT,
"interaction.author.contributions" TEXT,
"interaction.author.friends_count" TEXT,
"interaction.author.hash_id" TEXT,
"interaction.author.id" BIGINT,
"interaction.author.link" TEXT,
"interaction.author.name" TEXT,
"interaction.author.talk" TEXT,
"interaction.author.url" TEXT,
"interaction.author.username" TEXT,
"interaction.content" TEXT,
"interaction.contenttype" TEXT,
"interaction.created_at" DATE,
"interaction.geo.latitude" FLOAT,
"interaction.geo.longitude" FLOAT,
"interaction.hashtags" TEXT[],
"interaction.id" TEXT,
"interaction.link" TEXT,
"interaction.mentions" TEXT[],
"interaction.schema.version" INT,
"interaction.source" TEXT,
"interaction.tags" TEXT[],
"interaction.title" TEXT,
"interaction.type" TEXT,
"interaction.subtype" TEXT,
"klout.score" INT,
"klout.topics" TEXT[],
"language.tag" TEXT,
"language.tag_extended" TEXT,
"language.confidence" INT,
"links.code" INT[],
"links.created_at" TEXT[],
"links.domain" TEXT[],
"links.meta.charset" TEXT[],
"links.meta.content_type" TEXT[],
"links.meta.description" TEXT[],
"links.meta.keywords" TEXT [],
"links.meta.lang" TEXT[],
"links.meta.opengraph.author" TEXT,
"links.meta.opengraph.city" TEXT,
"links.meta.opengraph.country" TEXT,
"links.meta.opengraph.director" TEXT,
"links.meta.opengraph.email" TEXT,
"links.meta.opengraph.fax_number" TEXT,
"links.meta.opengraph.image" TEXT,
"links.meta.opengraph.locality" TEXT,
"links.meta.opengraph.phone_number" TEXT,
"links.meta.opengraph.region" TEXT,
"links.meta.opengraph.site_name" TEXT,
"links.meta.opengraph.title" TEXT,
"links.meta.opengraph.type" TEXT,
"links.meta.standout" TEXT[],
"links.meta.twitter.card" TEXT,
"links.meta.twitter.description" TEXT,
"links.meta.twitter.creator" TEXT,
"links.meta.twitter.creator_id" TEXT,
"links.meta.twitter.image" TEXT,
"links.meta.twitter.image_height" TEXT,
"links.meta.twitter.image_width" TEXT,
"links.meta.twitter.player" TEXT,
"links.meta.twitter.player_height" TEXT,
"links.meta.twitter.player_stream" TEXT,
"links.meta.twitter.player_stream_content_type" TEXT,
"links.meta.twitter.player_width" TEXT,
"links.meta.twitter.site" TEXT,
"links.meta.twitter.site_id" TEXT,
"links.meta.twitter.title" TEXT,
"links.meta.twitter.url" TEXT,
"links.normalized_url" TEXT[],
"links.retweet_count" INT[],
"links.title" TEXT[],
"links.url" TEXT[],
"salience.content.entities.name" TEXT,
"salience.content.entities.type" TEXT,
"salience.content.entities.label" TEXT,
"salience.content.entities.sentiment" INT,
"salience.content.entities.evidence" INT,
"salience.content.entities.confident" INT,
"salience.content.entities.about" INT,
"salience.content.entities.themes" TEXT[],
"salience.content.sentiment" BIGINT,
"salience.content.topics.name" TEXT,
"salience.content.topics.hits" INT,
"salience.content.topics.score" FLOAT,
"salience.title.entities.name" TEXT,
"salience.title.entities.type" TEXT,
"salience.title.entities.label" TEXT,
"salience.title.entities.sentiment" INT,
"salience.title.entities.evidence" INT,
"salience.title.entities.confident" INT,
"salience.title.entities.about" INT,
"salience.title.entities.themes" TEXT[],
"salience.title.sentiment" BIGINT,
"salience.title.topics.name" TEXT,
"salience.title.topics.hits" INT,
"salience.title.topics.score" FLOAT,	
"twitter.created_at" TEXT,
"twitter.domains" TEXT[],
"twitter.geo.latitude" FLOAT,
"twitter.geo.longitude" FLOAT,
"twitter.hashtags" TEXT[],
"twitter.id" TEXT,
"twitter.in_reply_to_screen_name" TEXT,
"twitter.in_reply_to_status_id" TEXT,
"twitter.in_reply_to_user_id" TEXT,
"twitter.links" TEXT[],
"twitter.media.display_url" TEXT,
"twitter.media.expanded_url" TEXT,
"twitter.media.id" INT,
"twitter.media.id_str" TEXT,
"twitter.media.media_url" TEXT,
"twitter.media.media_url_https" TEXT,
"twitter.media.source_status_id" INT,
"twitter.media.source_status_id_str" TEXT,
"twitter.media.type" TEXT,
"twitter.media.url" TEXT,
"twitter.mention_ids" BIGINT[],
"twitter.mentions" TEXT[],
"twitter.place.attributes.locality" TEXT,
"twitter.place.attributes.region" TEXT,
"twitter.place.attributes.street_address" TEXT,
"twitter.place.country" TEXT,
"twitter.place.country_code" TEXT,
"twitter.place.full_name" TEXT,
"twitter.place.id" TEXT,
"twitter.place.name" TEXT,
"twitter.place.place_type" TEXT,
"twitter.place.url" TEXT,
"twitter.retweet.count" INT,
"twitter.retweet.created_at" TEXT,
"twitter.retweet.domains" TEXT[],
"twitter.retweet.hashtags" TEXT[],
"twitter.retweet.id" TEXT,
"twitter.retweet.links" TEXT[],
"twitter.retweet.media.display_url" TEXT,
"twitter.retweet.media.expanded_url" TEXT,
"twitter.retweet.media.id" INT,
"twitter.retweet.media.id_str" TEXT,
"twitter.retweet.media.media_url" TEXT,
"twitter.retweet.media.media_url_https" TEXT,
"twitter.retweet.media.source_status_id" INT,
"twitter.retweet.media.source_status_id_str" TEXT,
"twitter.retweet.media.type" TEXT,
"twitter.retweet.media.url" TEXT,
"twitter.retweet.mention_ids" BIGINT[],
"twitter.retweet.mentions" TEXT[],
"twitter.retweet.place.country" TEXT,
"twitter.retweet.place.country_code" TEXT,
"twitter.retweet.place.full_name" TEXT,
"twitter.retweet.place.id" TEXT,
"twitter.retweet.place.name" TEXT,
"twitter.retweet.place.place_type" TEXT,
"twitter.retweet.place.url" TEXT,
"twitter.retweet.source" TEXT,
"twitter.retweet.text" TEXT,
"twitter.retweet.user.created_at" TEXT,
"twitter.retweet.user.description" TEXT,
"twitter.retweet.favourites_count" INT,
"twitter.retweet.user.followers_count" INT,
"twitter.retweet.user.friends_count" INT,
"twitter.retweet.user.geo_enabled" BOOLEAN,
"twitter.retweet.user.hash_id" TEXT,
"twitter.retweet.user.id" BIGINT,
"twitter.retweet.user.id_str" TEXT,
"twitter.retweet.user.lang" TEXT,
"twitter.retweet.user.listed_count" INT,
"twitter.retweet.user.location" TEXT,
"twitter.retweet.user.name" TEXT,
"twitter.retweet.user.profile_image_url" TEXT,
"twitter.retweet.user.screen_name" TEXT,
"twitter.retweet.user.statuses_count" INT,
"twitter.retweet.user.time_zone" TEXT,
"twitter.retweet.user.url" TEXT,
"twitter.retweet.user.utc_offset" INT,
"twitter.retweet.user.verified" BOOLEAN,
"twitter.retweeted.created_at" TEXT,
"twitter.retweeted.geo.latitude" FLOAT,
"twitter.retweeted.geo.longitude" FLOAT,
"twitter.retweeted.id" TEXT,
"twitter.retweeted.place.attributes.locality" TEXT,
"twitter.retweeted.place.attributes.region" TEXT,
"twitter.retweeted.place.attributes.street_address" TEXT,
"twitter.retweeted.place.country" TEXT,
"twitter.retweeted.place.country_code" TEXT,
"twitter.retweeted.place.full_name" TEXT,
"twitter.retweeted.place.id" TEXT,
"twitter.retweeted.place.name" TEXT,
"twitter.retweeted.place.place_type" TEXT,
"twitter.retweeted.place.url" TEXT,
"twitter.retweeted.source" TEXT,
"twitter.retweeted.user.created_at" TEXT,
"twitter.retweeted.user.description" TEXT,
"twitter.retweeted.favourites_count" INT,
"twitter.retweeted.user.followers_count" INT,
"twitter.retweeted.user.friends_count" INT,
"twitter.retweeted.user.geo_enabled" BOOLEAN,
"twitter.retweeted.user.hash_id" TEXT,
"twitter.retweeted.user.id" BIGINT,
"twitter.retweeted.user.id_str" TEXT,
"twitter.retweeted.user.lang" TEXT,
"twitter.retweeted.user.listed_count" INT,
"twitter.retweeted.user.location" TEXT,
"twitter.retweeted.user.name" TEXT,
"twitter.retweeted.user.profile_image_url" TEXT,
"twitter.retweeted.user.screen_name" TEXT,
"twitter.retweeted.user.statuses_count" INT,
"twitter.retweeted.user.time_zone" TEXT,
"twitter.retweeted.user.url" TEXT,
"twitter.retweeted.user.utc_offset" INT,
"twitter.retweeted.user.verified" BOOLEAN,
"twitter.source" TEXT,
"twitter.status" TEXT,
"twitter.text" TEXT,
"twitter.user.created_at" TEXT,
"twitter.user.description" TEXT,
"twitter.user.favourites_count" INT,
"twitter.user.followers_count" INT,
"twitter.user.friends_count" INT,
"twitter.user.geo_enabled" BOOLEAN,
"twitter.user.hash_id" TEXT,
"twitter.user.id" BIGINT,
"twitter.user.id_str" TEXT,
"twitter.user.lang" TEXT,
"twitter.user.listed_count" INT,
"twitter.user.location" TEXT,
"twitter.user.name" TEXT,
"twitter.user.profile_image_url" TEXT,
"twitter.user.screen_name" TEXT,
"twitter.user.statuses_count" INT,
"twitter.user.time_zone" TEXT,
"twitter.user.url" TEXT,
"twitter.user.utc_offset" INT,
"twitter.user.verified" BOOLEAN,
"interaction.tag_tree.BRAND" TEXT []
)
;

INSERT INTO explore_set
select * from json_tmp;


/***********************************************
Creates table explore_brand 
************************************************/
DROP TABLE IF EXISTS explore_brand
;

CREATE table explore_brand as 
SELECT 
"a"."demographic.gender",
"a"."facebook.application",
"a"."facebook.author.avatar",
"a"."facebook.author.id",
"a"."facebook.author.link",
"a"."facebook.author.name",
"a"."facebook.caption",
"a"."facebook.created_at",
"a"."facebook.description"	,
"a"."facebook.icon"	,
"a"."facebook.id",
"a"."facebook.likes.count",
"a"."facebook.likes.ids",
"a"."facebook.likes.names",
"a"."facebook.link"	,
"a"."facebook.message",
"a"."facebook.name"	,
"a"."facebook.og.app",
"a"."facebook.og.by",
"a"."facebook.og.length",
"a"."facebook.og.page",
"a"."facebook.og.photos",
"a"."facebook.picture",
"a"."facebook.place.id",
"a"."facebook.place.location.city",
"a"."facebook.place.location.country",
"a"."facebook.place.location.latitude",
"a"."facebook.place.location.longitude",
"a"."facebook.place.location.state",
"a"."facebook.place.location.street",
"a"."facebook.place.location.zip",
"a"."facebook.place.name",
"a"."facebook.source",
"a"."facebook.story",
"a"."facebook.story_tags.id",
"a"."facebook.story_tags.length",
"a"."facebook.story_tags.name",
"a"."facebook.story_tags.offset",
"a"."facebook.story_tags.type",
"a"."facebook.to.ids",
"a"."facebook.to.names",
"a"."facebook.type"	,
"a"."interaction.author.avatar",
"a"."interaction.author.contributions",
"a"."interaction.author.friends_count",
"a"."interaction.author.hash_id",
"a"."interaction.author.id",
"a"."interaction.author.link",
"a"."interaction.author.name",
"a"."interaction.author.talk",
"a"."interaction.author.url",
"a"."interaction.author.username",
"a"."interaction.content",
"a"."interaction.contenttype",
"a"."interaction.created_at",
"a"."interaction.geo.latitude",
"a"."interaction.geo.longitude",
"a"."interaction.hashtags",
"a"."interaction.id",
"a"."interaction.link",
"a"."interaction.mentions",
"a"."interaction.schema.version",
"a"."interaction.source",
"a"."interaction.tags",
"a"."interaction.title",
"a"."interaction.type",
"a"."interaction.subtype",
"a"."links.code",
"a"."links.created_at",
"a"."links.domain",
"a"."links.title",
"a"."links.url",
"a"."salience.content.sentiment",
"a"."twitter.created_at",
"a"."twitter.domains",
"a"."twitter.geo.latitude",
"a"."twitter.geo.longitude",
"a"."twitter.hashtags",
"a"."twitter.id",
"a"."twitter.in_reply_to_screen_name",
"a"."twitter.in_reply_to_status_id",
"a"."twitter.in_reply_to_user_id",
"a"."twitter.links",
"a"."twitter.media.display_url",
"a"."twitter.media.expanded_url",
"a"."twitter.media.id",
"a"."twitter.media.id_str",
"a"."twitter.media.media_url",
"a"."twitter.media.media_url_https",
"a"."twitter.media.source_status_id",
"a"."twitter.media.source_status_id_str",
"a"."twitter.media.type",
"a"."twitter.media.url",
"a"."twitter.mention_ids",
"a"."twitter.mentions",
"a"."twitter.place.attributes.locality",
"a"."twitter.place.attributes.region",
"a"."twitter.place.attributes.street_address",
"a"."twitter.place.country",
"a"."twitter.place.country_code",
"a"."twitter.place.full_name",
"a"."twitter.place.id",
"a"."twitter.place.name",
"a"."twitter.place.place_type",
"a"."twitter.place.url",
"a"."twitter.retweet.count",
"a"."twitter.retweet.created_at",
"a"."twitter.retweet.domains",
"a"."twitter.retweet.hashtags",
"a"."twitter.retweet.id",
"a"."twitter.retweet.links",
"a"."twitter.retweet.media.display_url",
"a"."twitter.retweet.media.expanded_url",
"a"."twitter.retweet.media.id",
"a"."twitter.retweet.media.id_str",
"a"."twitter.retweet.media.media_url",
"a"."twitter.retweet.media.media_url_https",
"a"."twitter.retweet.media.source_status_id",
"a"."twitter.retweet.media.source_status_id_str",
"a"."twitter.retweet.media.type",
"a"."twitter.retweet.media.url",
"a"."twitter.retweet.mention_ids",
"a"."twitter.retweet.mentions",
"a"."twitter.retweet.place.country",
"a"."twitter.retweet.place.country_code",
"a"."twitter.retweet.place.full_name",
"a"."twitter.retweet.place.id",
"a"."twitter.retweet.place.name",
"a"."twitter.retweet.place.place_type",
"a"."twitter.retweet.place.url",
"a"."twitter.retweet.source",
"a"."twitter.retweet.text",
"a"."twitter.retweet.user.created_at",
"a"."twitter.retweet.user.description",
"a"."twitter.retweet.favourites_count",
"a"."twitter.retweet.user.followers_count",
"a"."twitter.retweet.user.friends_count",
"a"."twitter.retweet.user.geo_enabled",
"a"."twitter.retweet.user.hash_id",
"a"."twitter.retweet.user.id",
"a"."twitter.retweet.user.id_str",
"a"."twitter.retweet.user.lang",
"a"."twitter.retweet.user.listed_count",
"a"."twitter.retweet.user.location",
"a"."twitter.retweet.user.name",
"a"."twitter.retweet.user.profile_image_url",
"a"."twitter.retweet.user.screen_name",
"a"."twitter.retweet.user.statuses_count",
"a"."twitter.retweet.user.time_zone",
"a"."twitter.retweet.user.url",
"a"."twitter.retweet.user.utc_offset",
"a"."twitter.retweet.user.verified",
"a"."twitter.retweeted.created_at",
"a"."twitter.retweeted.geo.latitude",
"a"."twitter.retweeted.geo.longitude",
"a"."twitter.retweeted.id",
"a"."twitter.retweeted.place.attributes.locality",
"a"."twitter.retweeted.place.attributes.region",
"a"."twitter.retweeted.place.attributes.street_address",
"a"."twitter.retweeted.place.country",
"a"."twitter.retweeted.place.country_code",
"a"."twitter.retweeted.place.full_name",
"a"."twitter.retweeted.place.id",
"a"."twitter.retweeted.place.name",
"a"."twitter.retweeted.place.place_type",
"a"."twitter.retweeted.place.url",
"a"."twitter.retweeted.source",
"a"."twitter.retweeted.user.created_at",
"a"."twitter.retweeted.user.description",
"a"."twitter.retweeted.favourites_count",
"a"."twitter.retweeted.user.followers_count",
"a"."twitter.retweeted.user.friends_count",
"a"."twitter.retweeted.user.geo_enabled",
"a"."twitter.retweeted.user.hash_id",
"a"."twitter.retweeted.user.id",
"a"."twitter.retweeted.user.id_str",
"a"."twitter.retweeted.user.lang",
"a"."twitter.retweeted.user.listed_count",
"a"."twitter.retweeted.user.location",
"a"."twitter.retweeted.user.name",
"a"."twitter.retweeted.user.profile_image_url",
"a"."twitter.retweeted.user.screen_name",
"a"."twitter.retweeted.user.statuses_count",
"a"."twitter.retweeted.user.time_zone",
"a"."twitter.retweeted.user.url",
"a"."twitter.retweeted.user.utc_offset",
"a"."twitter.retweeted.user.verified",
"a"."twitter.source",
"a"."twitter.status",
"a"."twitter.text",
"a"."twitter.user.created_at",
"a"."twitter.user.description",
"a"."twitter.user.favourites_count",
"a"."twitter.user.followers_count",
"a"."twitter.user.friends_count",
"a"."twitter.user.geo_enabled",
"a"."twitter.user.hash_id",
"a"."twitter.user.id",
"a"."twitter.user.id_str",
"a"."twitter.user.lang",
"a"."twitter.user.listed_count",
"a"."twitter.user.location",
"a"."twitter.user.name",
"a"."twitter.user.profile_image_url",
"a"."twitter.user.screen_name",
"a"."twitter.user.statuses_count",
"a"."twitter.user.time_zone",
"a"."twitter.user.url",
"a"."twitter.user.utc_offset",
"a"."twitter.user.verified",
case when "a"."interaction.tag_tree.BRAND" is NULL then ''
else unnest("a"."interaction.tag_tree.BRAND")
end as "interaction.tag_tree.BRAND"
from explore_set a
where cast("a"."interaction.tag_tree.BRAND" as text) is NOT NULL
;


/*******************************
creates table explore_mentions
*******************************/

DROP TABLE IF EXISTS explore_mentions
;

CREATE TABLE explore_mentions as
SELECT
"a"."demographic.gender",
"a"."facebook.application",
"a"."facebook.author.avatar",
"a"."facebook.author.id",
"a"."facebook.author.link",
"a"."facebook.author.name",
"a"."facebook.caption",
"a"."facebook.created_at",
"a"."facebook.description",
"a"."facebook.icon",
"a"."facebook.id",
"a"."facebook.likes.count",
"a"."facebook.likes.ids",
"a"."facebook.likes.names",
"a"."facebook.link",
"a"."facebook.message",
"a"."facebook.name",
"a"."facebook.og.app",
"a"."facebook.og.by",
"a"."facebook.og.length",
"a"."facebook.og.page",
"a"."facebook.og.photos",
"a"."facebook.picture",
"a"."facebook.place.id",
"a"."facebook.place.location.city",
"a"."facebook.place.location.country",
"a"."facebook.place.location.latitude",
"a"."facebook.place.location.longitude",
"a"."facebook.place.location.state",
"a"."facebook.place.location.street",
"a"."facebook.place.location.zip",
"a"."facebook.place.name",
"a"."facebook.source",
"a"."facebook.story",
"a"."facebook.story_tags.id",
"a"."facebook.story_tags.length",
"a"."facebook.story_tags.name",
"a"."facebook.story_tags.offset",
"a"."facebook.story_tags.type",
"a"."facebook.to.ids",
"a"."facebook.to.names",
"a"."facebook.type"	,
"a"."interaction.author.avatar",
"a"."interaction.author.contributions",
"a"."interaction.author.friends_count",
"a"."interaction.author.hash_id",
"a"."interaction.author.id",
"a"."interaction.author.link",
"a"."interaction.author.name",
"a"."interaction.author.talk",
"a"."interaction.author.url",
"a"."interaction.author.username",
"a"."interaction.content",
"a"."interaction.contenttype",
"a"."interaction.created_at",
"a"."interaction.geo.latitude",
"a"."interaction.geo.longitude",
"a"."interaction.hashtags",
"a"."interaction.id",
"a"."interaction.link",
"a"."interaction.mentions",
"a"."interaction.schema.version",
"a"."interaction.source",
"a"."interaction.tags",
"a"."interaction.title",
"a"."interaction.type",
"a"."interaction.subtype",
"a"."links.code",
"a"."links.created_at",
"a"."links.domain",
"a"."links.title",
"a"."links.url",
"a"."salience.content.sentiment",
"a"."twitter.created_at",
"a"."twitter.domains",
"a"."twitter.geo.latitude",
"a"."twitter.geo.longitude",
"a"."twitter.hashtags",
"a"."twitter.id",
"a"."twitter.in_reply_to_screen_name",
"a"."twitter.in_reply_to_status_id",
"a"."twitter.in_reply_to_user_id",
"a"."twitter.links",
"a"."twitter.media.display_url",
"a"."twitter.media.expanded_url",
"a"."twitter.media.id",
"a"."twitter.media.id_str",
"a"."twitter.media.media_url",
"a"."twitter.media.media_url_https",
"a"."twitter.media.source_status_id",
"a"."twitter.media.source_status_id_str",
"a"."twitter.media.type",
"a"."twitter.media.url",
"a"."twitter.mention_ids",
"a"."twitter.mentions",
"a"."twitter.place.attributes.locality",
"a"."twitter.place.attributes.region",
"a"."twitter.place.attributes.street_address",
"a"."twitter.place.country",
"a"."twitter.place.country_code",
"a"."twitter.place.full_name",
"a"."twitter.place.id",
"a"."twitter.place.name",
"a"."twitter.place.place_type",
"a"."twitter.place.url",
"a"."twitter.retweet.count",
"a"."twitter.retweet.created_at",
"a"."twitter.retweet.domains",
"a"."twitter.retweet.hashtags",
"a"."twitter.retweet.id",
"a"."twitter.retweet.links",
"a"."twitter.retweet.media.display_url",
"a"."twitter.retweet.media.expanded_url",
"a"."twitter.retweet.media.id",
"a"."twitter.retweet.media.id_str",
"a"."twitter.retweet.media.media_url",
"a"."twitter.retweet.media.media_url_https",
"a"."twitter.retweet.media.source_status_id",
"a"."twitter.retweet.media.source_status_id_str",
"a"."twitter.retweet.media.type",
"a"."twitter.retweet.media.url",
"a"."twitter.retweet.mention_ids",
"a"."twitter.retweet.mentions",
"a"."twitter.retweet.place.country",
"a"."twitter.retweet.place.country_code",
"a"."twitter.retweet.place.full_name",
"a"."twitter.retweet.place.id",
"a"."twitter.retweet.place.name",
"a"."twitter.retweet.place.place_type",
"a"."twitter.retweet.place.url",
"a"."twitter.retweet.source",
"a"."twitter.retweet.text",
"a"."twitter.retweet.user.created_at",
"a"."twitter.retweet.user.description",
"a"."twitter.retweet.favourites_count",
"a"."twitter.retweet.user.followers_count",
"a"."twitter.retweet.user.friends_count",
"a"."twitter.retweet.user.geo_enabled",
"a"."twitter.retweet.user.hash_id",
"a"."twitter.retweet.user.id",
"a"."twitter.retweet.user.id_str",
"a"."twitter.retweet.user.lang",
"a"."twitter.retweet.user.listed_count",
"a"."twitter.retweet.user.location",
"a"."twitter.retweet.user.name",
"a"."twitter.retweet.user.profile_image_url",
"a"."twitter.retweet.user.screen_name",
"a"."twitter.retweet.user.statuses_count",
"a"."twitter.retweet.user.time_zone",
"a"."twitter.retweet.user.url",
"a"."twitter.retweet.user.utc_offset",
"a"."twitter.retweet.user.verified",
"a"."twitter.retweeted.created_at",
"a"."twitter.retweeted.geo.latitude",
"a"."twitter.retweeted.geo.longitude",
"a"."twitter.retweeted.id",
"a"."twitter.retweeted.place.attributes.locality",
"a"."twitter.retweeted.place.attributes.region",
"a"."twitter.retweeted.place.attributes.street_address",
"a"."twitter.retweeted.place.country",
"a"."twitter.retweeted.place.country_code",
"a"."twitter.retweeted.place.full_name",
"a"."twitter.retweeted.place.id",
"a"."twitter.retweeted.place.name",
"a"."twitter.retweeted.place.place_type",
"a"."twitter.retweeted.place.url",
"a"."twitter.retweeted.source",
"a"."twitter.retweeted.user.created_at",
"a"."twitter.retweeted.user.description",
"a"."twitter.retweeted.favourites_count",
"a"."twitter.retweeted.user.followers_count",
"a"."twitter.retweeted.user.friends_count",
"a"."twitter.retweeted.user.geo_enabled",
"a"."twitter.retweeted.user.hash_id",
"a"."twitter.retweeted.user.id",
"a"."twitter.retweeted.user.id_str",
"a"."twitter.retweeted.user.lang",
"a"."twitter.retweeted.user.listed_count",
"a"."twitter.retweeted.user.location",
"a"."twitter.retweeted.user.name",
"a"."twitter.retweeted.user.profile_image_url",
"a"."twitter.retweeted.user.screen_name",
"a"."twitter.retweeted.user.statuses_count",
"a"."twitter.retweeted.user.time_zone",
"a"."twitter.retweeted.user.url",
"a"."twitter.retweeted.user.utc_offset",
"a"."twitter.retweeted.user.verified",
"a"."twitter.source",
"a"."twitter.status",
"a"."twitter.text",
"a"."twitter.user.created_at",
"a"."twitter.user.description",
"a"."twitter.user.favourites_count",
"a"."twitter.user.followers_count",
"a"."twitter.user.friends_count",
"a"."twitter.user.geo_enabled",
"a"."twitter.user.hash_id",
"a"."twitter.user.id",
"a"."twitter.user.id_str",
"a"."twitter.user.lang",
"a"."twitter.user.listed_count",
"a"."twitter.user.location",
"a"."twitter.user.name",
"a"."twitter.user.profile_image_url",
"a"."twitter.user.screen_name",
"a"."twitter.user.statuses_count",
"a"."twitter.user.time_zone",
"a"."twitter.user.url",
"a"."twitter.user.utc_offset",
"a"."twitter.user.verified",
CASE when "a"."interaction.tag_tree.BRAND" is NULL then ''
ELSE unnest("a"."interaction.tag_tree.BRAND")
END AS "interaction.tag_tree.BRAND"
from   (SELECT 
	"demographic.gender",
	"facebook.application",
	"facebook.author.avatar",
	"facebook.author.id",
	"facebook.author.link",
	"facebook.author.name",
	"facebook.caption",
	"facebook.created_at",
	"facebook.description"	,
	"facebook.icon"	,
	"facebook.id",
	"facebook.likes.count",
	"facebook.likes.ids",
	"facebook.likes.names",
	"facebook.link"	,
	"facebook.message",
	"facebook.name"	,
	"facebook.og.app",
	"facebook.og.by",
	"facebook.og.length",
	"facebook.og.page",
	"facebook.og.photos",
	"facebook.picture",
	"facebook.place.id",
	"facebook.place.location.city",
	"facebook.place.location.country",
	"facebook.place.location.latitude",
	"facebook.place.location.longitude",
	"facebook.place.location.state",
	"facebook.place.location.street",
	"facebook.place.location.zip",
	"facebook.place.name",
	"facebook.source",
	"facebook.story",
	"facebook.story_tags.id",
	"facebook.story_tags.length",
	"facebook.story_tags.name",
	"facebook.story_tags.offset",
	"facebook.story_tags.type",
	"facebook.to.ids",
	"facebook.to.names",
	"facebook.type"	,
	"interaction.author.avatar",
	"interaction.author.contributions",
	"interaction.author.friends_count",
	"interaction.author.hash_id",
	"interaction.author.id",
	"interaction.author.link",
	"interaction.author.name",
	"interaction.author.talk",
	"interaction.author.url",
	"interaction.author.username",
	"interaction.content",
	"interaction.contenttype",
	"interaction.created_at",
	"interaction.geo.latitude",
	"interaction.geo.longitude",
	"interaction.hashtags",
	"interaction.id",
	"interaction.link",
	"interaction.schema.version",
	"interaction.source",
	"interaction.tags",
	"interaction.title",
	"interaction.type",
	"interaction.subtype",
	"links.code",
	"links.created_at",
	"links.domain",
	"links.title",
	"links.url",
	"salience.content.sentiment",
	"twitter.created_at",
	"twitter.domains",
	"twitter.geo.latitude",
	"twitter.geo.longitude",
	"twitter.hashtags",
	"twitter.id",
	"twitter.in_reply_to_screen_name",
	"twitter.in_reply_to_status_id",
	"twitter.in_reply_to_user_id",
	"twitter.links",
	"twitter.media.display_url",
	"twitter.media.expanded_url",
	"twitter.media.id",
	"twitter.media.id_str",
	"twitter.media.media_url",
	"twitter.media.media_url_https",
	"twitter.media.source_status_id",
	"twitter.media.source_status_id_str",
	"twitter.media.type",
	"twitter.media.url",
	"twitter.mention_ids",
	"twitter.mentions",
	"twitter.place.attributes.locality",
	"twitter.place.attributes.region",
	"twitter.place.attributes.street_address",
	"twitter.place.country",
	"twitter.place.country_code",
	"twitter.place.full_name",
	"twitter.place.id",
	"twitter.place.name",
	"twitter.place.place_type",
	"twitter.place.url",
	"twitter.retweet.count",
	"twitter.retweet.created_at",
	"twitter.retweet.domains",
	"twitter.retweet.hashtags",
	"twitter.retweet.id",
	"twitter.retweet.links",
	"twitter.retweet.media.display_url",
	"twitter.retweet.media.expanded_url",
	"twitter.retweet.media.id",
	"twitter.retweet.media.id_str",
	"twitter.retweet.media.media_url",
	"twitter.retweet.media.media_url_https",
	"twitter.retweet.media.source_status_id",
	"twitter.retweet.media.source_status_id_str",
	"twitter.retweet.media.type",
	"twitter.retweet.media.url",
	"twitter.retweet.mention_ids",
	"twitter.retweet.mentions",
	"twitter.retweet.place.country",
	"twitter.retweet.place.country_code",
	"twitter.retweet.place.full_name",
	"twitter.retweet.place.id",
	"twitter.retweet.place.name",
	"twitter.retweet.place.place_type",
	"twitter.retweet.place.url",
	"twitter.retweet.source",
	"twitter.retweet.text",
	"twitter.retweet.user.created_at",
	"twitter.retweet.user.description",
	"twitter.retweet.favourites_count",
	"twitter.retweet.user.followers_count",
	"twitter.retweet.user.friends_count",
	"twitter.retweet.user.geo_enabled",
	"twitter.retweet.user.hash_id",
	"twitter.retweet.user.id",
	"twitter.retweet.user.id_str",
	"twitter.retweet.user.lang",
	"twitter.retweet.user.listed_count",
	"twitter.retweet.user.location",
	"twitter.retweet.user.name",
	"twitter.retweet.user.profile_image_url",
	"twitter.retweet.user.screen_name",
	"twitter.retweet.user.statuses_count",
	"twitter.retweet.user.time_zone",
	"twitter.retweet.user.url",
	"twitter.retweet.user.utc_offset",
	"twitter.retweet.user.verified",
	"twitter.retweeted.created_at",
	"twitter.retweeted.geo.latitude",
	"twitter.retweeted.geo.longitude",
	"twitter.retweeted.id",
	"twitter.retweeted.place.attributes.locality",
	"twitter.retweeted.place.attributes.region",
	"twitter.retweeted.place.attributes.street_address",
	"twitter.retweeted.place.country",
	"twitter.retweeted.place.country_code",
	"twitter.retweeted.place.full_name",
	"twitter.retweeted.place.id",
	"twitter.retweeted.place.name",
	"twitter.retweeted.place.place_type",
	"twitter.retweeted.place.url",
	"twitter.retweeted.source",
	"twitter.retweeted.user.created_at",
	"twitter.retweeted.user.description",
	"twitter.retweeted.favourites_count",
	"twitter.retweeted.user.followers_count",
	"twitter.retweeted.user.friends_count",
	"twitter.retweeted.user.geo_enabled",
	"twitter.retweeted.user.hash_id",
	"twitter.retweeted.user.id",
	"twitter.retweeted.user.id_str",
	"twitter.retweeted.user.lang",
	"twitter.retweeted.user.listed_count",
	"twitter.retweeted.user.location",
	"twitter.retweeted.user.name",
	"twitter.retweeted.user.profile_image_url",
	"twitter.retweeted.user.screen_name",
	"twitter.retweeted.user.statuses_count",
	"twitter.retweeted.user.time_zone",
	"twitter.retweeted.user.url",
	"twitter.retweeted.user.utc_offset",
	"twitter.retweeted.user.verified",
	"twitter.source",
	"twitter.status",
	"twitter.text",
	"twitter.user.created_at",
	"twitter.user.description",
	"twitter.user.favourites_count",
	"twitter.user.followers_count",
	"twitter.user.friends_count",
	"twitter.user.geo_enabled",
	"twitter.user.hash_id",
	"twitter.user.id",
	"twitter.user.id_str",
	"twitter.user.lang",
	"twitter.user.listed_count",
	"twitter.user.location",
	"twitter.user.name",
	"twitter.user.profile_image_url",
	"twitter.user.screen_name",
	"twitter.user.statuses_count",
	"twitter.user.time_zone",
	"twitter.user.url",
	"twitter.user.utc_offset",
	"twitter.user.verified",
	"interaction.tag_tree.BRAND",
	CASE WHEN "interaction.mentions" is NULL then ''
	ELSE unnest("interaction.mentions")
	END AS "interaction.mentions"
	from explore_set
	where cast("interaction.mentions" as text) is NOT NULL
) a
;

/*********************************
create table explore_hashtags
***********************************/
DROP TABLE IF EXISTS explore_hashtags
;

CREATE TABLE explore_hashtags as
SELECT
"a"."demographic.gender",
"a"."facebook.application",
"a"."facebook.author.avatar",
"a"."facebook.author.id",
"a"."facebook.author.link",
"a"."facebook.author.name",
"a"."facebook.caption",
"a"."facebook.created_at",
"a"."facebook.description"	,
"a"."facebook.icon"	,
"a"."facebook.id",
"a"."facebook.likes.count",
"a"."facebook.likes.ids",
"a"."facebook.likes.names",
"a"."facebook.link"	,
"a"."facebook.message",
"a"."facebook.name"	,
"a"."facebook.og.app",
"a"."facebook.og.by",
"a"."facebook.og.length",
"a"."facebook.og.page",
"a"."facebook.og.photos",
"a"."facebook.picture",
"a"."facebook.place.id",
"a"."facebook.place.location.city",
"a"."facebook.place.location.country",
"a"."facebook.place.location.latitude",
"a"."facebook.place.location.longitude",
"a"."facebook.place.location.state",
"a"."facebook.place.location.street",
"a"."facebook.place.location.zip",
"a"."facebook.place.name",
"a"."facebook.source",
"a"."facebook.story",
"a"."facebook.story_tags.id",
"a"."facebook.story_tags.length",
"a"."facebook.story_tags.name",
"a"."facebook.story_tags.offset",
"a"."facebook.story_tags.type",
"a"."facebook.to.ids",
"a"."facebook.to.names",
"a"."facebook.type"	,
"a"."interaction.author.avatar",
"a"."interaction.author.contributions",
"a"."interaction.author.friends_count",
"a"."interaction.author.hash_id",
"a"."interaction.author.id",
"a"."interaction.author.link",
"a"."interaction.author.name",
"a"."interaction.author.talk",
"a"."interaction.author.url",
"a"."interaction.author.username",
"a"."interaction.content",
"a"."interaction.contenttype",
"a"."interaction.created_at",
"a"."interaction.geo.latitude",
"a"."interaction.geo.longitude",
"a"."interaction.hashtags",
"a"."interaction.id",
"a"."interaction.link",
"a"."interaction.mentions",
"a"."interaction.schema.version",
"a"."interaction.source",
"a"."interaction.tags",
"a"."interaction.title",
"a"."interaction.type",
"a"."interaction.subtype",
"a"."links.code",
"a"."links.created_at",
"a"."links.domain",
"a"."links.title",
"a"."links.url",
"a"."salience.content.sentiment",
"a"."twitter.created_at",
"a"."twitter.domains",
"a"."twitter.geo.latitude",
"a"."twitter.geo.longitude",
"a"."twitter.hashtags",
"a"."twitter.id",
"a"."twitter.in_reply_to_screen_name",
"a"."twitter.in_reply_to_status_id",
"a"."twitter.in_reply_to_user_id",
"a"."twitter.links",
"a"."twitter.media.display_url",
"a"."twitter.media.expanded_url",
"a"."twitter.media.id",
"a"."twitter.media.id_str",
"a"."twitter.media.media_url",
"a"."twitter.media.media_url_https",
"a"."twitter.media.source_status_id",
"a"."twitter.media.source_status_id_str",
"a"."twitter.media.type",
"a"."twitter.media.url",
"a"."twitter.mention_ids",
"a"."twitter.mentions",
"a"."twitter.place.attributes.locality",
"a"."twitter.place.attributes.region",
"a"."twitter.place.attributes.street_address",
"a"."twitter.place.country",
"a"."twitter.place.country_code",
"a"."twitter.place.full_name",
"a"."twitter.place.id",
"a"."twitter.place.name",
"a"."twitter.place.place_type",
"a"."twitter.place.url",
"a"."twitter.retweet.count",
"a"."twitter.retweet.created_at",
"a"."twitter.retweet.domains",
"a"."twitter.retweet.hashtags",
"a"."twitter.retweet.id",
"a"."twitter.retweet.links",
"a"."twitter.retweet.media.display_url",
"a"."twitter.retweet.media.expanded_url",
"a"."twitter.retweet.media.id",
"a"."twitter.retweet.media.id_str",
"a"."twitter.retweet.media.media_url",
"a"."twitter.retweet.media.media_url_https",
"a"."twitter.retweet.media.source_status_id",
"a"."twitter.retweet.media.source_status_id_str",
"a"."twitter.retweet.media.type",
"a"."twitter.retweet.media.url",
"a"."twitter.retweet.mention_ids",
"a"."twitter.retweet.mentions",
"a"."twitter.retweet.place.country",
"a"."twitter.retweet.place.country_code",
"a"."twitter.retweet.place.full_name",
"a"."twitter.retweet.place.id",
"a"."twitter.retweet.place.name",
"a"."twitter.retweet.place.place_type",
"a"."twitter.retweet.place.url",
"a"."twitter.retweet.source",
"a"."twitter.retweet.text",
"a"."twitter.retweet.user.created_at",
"a"."twitter.retweet.user.description",
"a"."twitter.retweet.favourites_count",
"a"."twitter.retweet.user.followers_count",
"a"."twitter.retweet.user.friends_count",
"a"."twitter.retweet.user.geo_enabled",
"a"."twitter.retweet.user.hash_id",
"a"."twitter.retweet.user.id",
"a"."twitter.retweet.user.id_str",
"a"."twitter.retweet.user.lang",
"a"."twitter.retweet.user.listed_count",
"a"."twitter.retweet.user.location",
"a"."twitter.retweet.user.name",
"a"."twitter.retweet.user.profile_image_url",
"a"."twitter.retweet.user.screen_name",
"a"."twitter.retweet.user.statuses_count",
"a"."twitter.retweet.user.time_zone",
"a"."twitter.retweet.user.url",
"a"."twitter.retweet.user.utc_offset",
"a"."twitter.retweet.user.verified",
"a"."twitter.retweeted.created_at",
"a"."twitter.retweeted.geo.latitude",
"a"."twitter.retweeted.geo.longitude",
"a"."twitter.retweeted.id",
"a"."twitter.retweeted.place.attributes.locality",
"a"."twitter.retweeted.place.attributes.region",
"a"."twitter.retweeted.place.attributes.street_address",
"a"."twitter.retweeted.place.country",
"a"."twitter.retweeted.place.country_code",
"a"."twitter.retweeted.place.full_name",
"a"."twitter.retweeted.place.id",
"a"."twitter.retweeted.place.name",
"a"."twitter.retweeted.place.place_type",
"a"."twitter.retweeted.place.url",
"a"."twitter.retweeted.source",
"a"."twitter.retweeted.user.created_at",
"a"."twitter.retweeted.user.description",
"a"."twitter.retweeted.favourites_count",
"a"."twitter.retweeted.user.followers_count",
"a"."twitter.retweeted.user.friends_count",
"a"."twitter.retweeted.user.geo_enabled",
"a"."twitter.retweeted.user.hash_id",
"a"."twitter.retweeted.user.id",
"a"."twitter.retweeted.user.id_str",
"a"."twitter.retweeted.user.lang",
"a"."twitter.retweeted.user.listed_count",
"a"."twitter.retweeted.user.location",
"a"."twitter.retweeted.user.name",
"a"."twitter.retweeted.user.profile_image_url",
"a"."twitter.retweeted.user.screen_name",
"a"."twitter.retweeted.user.statuses_count",
"a"."twitter.retweeted.user.time_zone",
"a"."twitter.retweeted.user.url",
"a"."twitter.retweeted.user.utc_offset",
"a"."twitter.retweeted.user.verified",
"a"."twitter.source",
"a"."twitter.status",
"a"."twitter.text",
"a"."twitter.user.created_at",
"a"."twitter.user.description",
"a"."twitter.user.favourites_count",
"a"."twitter.user.followers_count",
"a"."twitter.user.friends_count",
"a"."twitter.user.geo_enabled",
"a"."twitter.user.hash_id",
"a"."twitter.user.id",
"a"."twitter.user.id_str",
"a"."twitter.user.lang",
"a"."twitter.user.listed_count",
"a"."twitter.user.location",
"a"."twitter.user.name",
"a"."twitter.user.profile_image_url",
"a"."twitter.user.screen_name",
"a"."twitter.user.statuses_count",
"a"."twitter.user.time_zone",
"a"."twitter.user.url",
"a"."twitter.user.utc_offset",
"a"."twitter.user.verified",
CASE when "a"."interaction.tag_tree.BRAND" is NULL then ''
ELSE unnest("a"."interaction.tag_tree.BRAND")
END AS "interaction.tag_tree.BRAND"
from   (SELECT 
	"demographic.gender",
	"facebook.application",
	"facebook.author.avatar",
	"facebook.author.id",
	"facebook.author.link",
	"facebook.author.name",
	"facebook.caption",
	"facebook.created_at",
	"facebook.description"	,
	"facebook.icon"	,
	"facebook.id",
	"facebook.likes.count",
	"facebook.likes.ids",
	"facebook.likes.names",
	"facebook.link"	,
	"facebook.message",
	"facebook.name"	,
	"facebook.og.app",
	"facebook.og.by",
	"facebook.og.length",
	"facebook.og.page",
	"facebook.og.photos",
	"facebook.picture",
	"facebook.place.id",
	"facebook.place.location.city",
	"facebook.place.location.country",
	"facebook.place.location.latitude",
	"facebook.place.location.longitude",
	"facebook.place.location.state",
	"facebook.place.location.street",
	"facebook.place.location.zip",
	"facebook.place.name",
	"facebook.source",
	"facebook.story",
	"facebook.story_tags.id",
	"facebook.story_tags.length",
	"facebook.story_tags.name",
	"facebook.story_tags.offset",
	"facebook.story_tags.type",
	"facebook.to.ids",
	"facebook.to.names",
	"facebook.type"	,
	"interaction.author.avatar",
	"interaction.author.contributions",
	"interaction.author.friends_count",
	"interaction.author.hash_id",
	"interaction.author.id",
	"interaction.author.link",
	"interaction.author.name",
	"interaction.author.talk",
	"interaction.author.url",
	"interaction.author.username",
	"interaction.content",
	"interaction.contenttype",
	"interaction.created_at",
	"interaction.geo.latitude",
	"interaction.geo.longitude",
	"interaction.id",
	"interaction.link",
	"interaction.mentions",
	"interaction.schema.version",
	"interaction.source",
	"interaction.tags",
	"interaction.title",
	"interaction.type",
	"interaction.subtype",
	"links.code",
	"links.created_at",
	"links.domain",
	"links.title",
	"links.url",
	"salience.content.sentiment",
	"twitter.created_at",
	"twitter.domains",
	"twitter.geo.latitude",
	"twitter.geo.longitude",
	"twitter.hashtags",
	"twitter.id",
	"twitter.in_reply_to_screen_name",
	"twitter.in_reply_to_status_id",
	"twitter.in_reply_to_user_id",
	"twitter.links",
	"twitter.media.display_url",
	"twitter.media.expanded_url",
	"twitter.media.id",
	"twitter.media.id_str",
	"twitter.media.media_url",
	"twitter.media.media_url_https",
	"twitter.media.source_status_id",
	"twitter.media.source_status_id_str",
	"twitter.media.type",
	"twitter.media.url",
	"twitter.mention_ids",
	"twitter.mentions",
	"twitter.place.attributes.locality",
	"twitter.place.attributes.region",
	"twitter.place.attributes.street_address",
	"twitter.place.country",
	"twitter.place.country_code",
	"twitter.place.full_name",
	"twitter.place.id",
	"twitter.place.name",
	"twitter.place.place_type",
	"twitter.place.url",
	"twitter.retweet.count",
	"twitter.retweet.created_at",
	"twitter.retweet.domains",
	"twitter.retweet.hashtags",
	"twitter.retweet.id",
	"twitter.retweet.links",
	"twitter.retweet.media.display_url",
	"twitter.retweet.media.expanded_url",
	"twitter.retweet.media.id",
	"twitter.retweet.media.id_str",
	"twitter.retweet.media.media_url",
	"twitter.retweet.media.media_url_https",
	"twitter.retweet.media.source_status_id",
	"twitter.retweet.media.source_status_id_str",
	"twitter.retweet.media.type",
	"twitter.retweet.media.url",
	"twitter.retweet.mention_ids",
	"twitter.retweet.mentions",
	"twitter.retweet.place.country",
	"twitter.retweet.place.country_code",
	"twitter.retweet.place.full_name",
	"twitter.retweet.place.id",
	"twitter.retweet.place.name",
	"twitter.retweet.place.place_type",
	"twitter.retweet.place.url",
	"twitter.retweet.source",
	"twitter.retweet.text",
	"twitter.retweet.user.created_at",
	"twitter.retweet.user.description",
	"twitter.retweet.favourites_count",
	"twitter.retweet.user.followers_count",
	"twitter.retweet.user.friends_count",
	"twitter.retweet.user.geo_enabled",
	"twitter.retweet.user.hash_id",
	"twitter.retweet.user.id",
	"twitter.retweet.user.id_str",
	"twitter.retweet.user.lang",
	"twitter.retweet.user.listed_count",
	"twitter.retweet.user.location",
	"twitter.retweet.user.name",
	"twitter.retweet.user.profile_image_url",
	"twitter.retweet.user.screen_name",
	"twitter.retweet.user.statuses_count",
	"twitter.retweet.user.time_zone",
	"twitter.retweet.user.url",
	"twitter.retweet.user.utc_offset",
	"twitter.retweet.user.verified",
	"twitter.retweeted.created_at",
	"twitter.retweeted.geo.latitude",
	"twitter.retweeted.geo.longitude",
	"twitter.retweeted.id",
	"twitter.retweeted.place.attributes.locality",
	"twitter.retweeted.place.attributes.region",
	"twitter.retweeted.place.attributes.street_address",
	"twitter.retweeted.place.country",
	"twitter.retweeted.place.country_code",
	"twitter.retweeted.place.full_name",
	"twitter.retweeted.place.id",
	"twitter.retweeted.place.name",
	"twitter.retweeted.place.place_type",
	"twitter.retweeted.place.url",
	"twitter.retweeted.source",
	"twitter.retweeted.user.created_at",
	"twitter.retweeted.user.description",
	"twitter.retweeted.favourites_count",
	"twitter.retweeted.user.followers_count",
	"twitter.retweeted.user.friends_count",
	"twitter.retweeted.user.geo_enabled",
	"twitter.retweeted.user.hash_id",
	"twitter.retweeted.user.id",
	"twitter.retweeted.user.id_str",
	"twitter.retweeted.user.lang",
	"twitter.retweeted.user.listed_count",
	"twitter.retweeted.user.location",
	"twitter.retweeted.user.name",
	"twitter.retweeted.user.profile_image_url",
	"twitter.retweeted.user.screen_name",
	"twitter.retweeted.user.statuses_count",
	"twitter.retweeted.user.time_zone",
	"twitter.retweeted.user.url",
	"twitter.retweeted.user.utc_offset",
	"twitter.retweeted.user.verified",
	"twitter.source",
	"twitter.status",
	"twitter.text",
	"twitter.user.created_at",
	"twitter.user.description",
	"twitter.user.favourites_count",
	"twitter.user.followers_count",
	"twitter.user.friends_count",
	"twitter.user.geo_enabled",
	"twitter.user.hash_id",
	"twitter.user.id",
	"twitter.user.id_str",
	"twitter.user.lang",
	"twitter.user.listed_count",
	"twitter.user.location",
	"twitter.user.name",
	"twitter.user.profile_image_url",
	"twitter.user.screen_name",
	"twitter.user.statuses_count",
	"twitter.user.time_zone",
	"twitter.user.url",
	"twitter.user.utc_offset",
	"twitter.user.verified",
	"interaction.tag_tree.BRAND",
	CASE WHEN "interaction.hashtags" is NULL then ''
	ELSE unnest("interaction.hashtags")
	END AS "interaction.hashtags"
	from explore_set
	where cast("interaction.hashtags" as text) is NOT NULL
) a
;

/***************************
create table explore_links
****************************/

DROP TABLE IF EXISTS explore_links
;

CREATE TABLE explore_links as
SELECT
"a"."demographic.gender",
"a"."facebook.application",
"a"."facebook.author.avatar",
"a"."facebook.author.id",
"a"."facebook.author.link",
"a"."facebook.author.name",
"a"."facebook.caption",
"a"."facebook.created_at",
"a"."facebook.description"	,
"a"."facebook.icon"	,
"a"."facebook.id",
"a"."facebook.likes.count",
"a"."facebook.likes.ids",
"a"."facebook.likes.names",
"a"."facebook.link"	,
"a"."facebook.message",
"a"."facebook.name"	,
"a"."facebook.og.app",
"a"."facebook.og.by",
"a"."facebook.og.length",
"a"."facebook.og.page",
"a"."facebook.og.photos",
"a"."facebook.picture",
"a"."facebook.place.id",
"a"."facebook.place.location.city",
"a"."facebook.place.location.country",
"a"."facebook.place.location.latitude",
"a"."facebook.place.location.longitude",
"a"."facebook.place.location.state",
"a"."facebook.place.location.street",
"a"."facebook.place.location.zip",
"a"."facebook.place.name",
"a"."facebook.source",
"a"."facebook.story",
"a"."facebook.story_tags.id",
"a"."facebook.story_tags.length",
"a"."facebook.story_tags.name",
"a"."facebook.story_tags.offset",
"a"."facebook.story_tags.type",
"a"."facebook.to.ids",
"a"."facebook.to.names",
"a"."facebook.type"	,
"a"."interaction.author.avatar",
"a"."interaction.author.contributions",
"a"."interaction.author.friends_count",
"a"."interaction.author.hash_id",
"a"."interaction.author.id",
"a"."interaction.author.link",
"a"."interaction.author.name",
"a"."interaction.author.talk",
"a"."interaction.author.url",
"a"."interaction.author.username",
"a"."interaction.content",
"a"."interaction.contenttype",
"a"."interaction.created_at",
"a"."interaction.geo.latitude",
"a"."interaction.geo.longitude",
"a"."interaction.hashtags",
"a"."interaction.id",
"a"."interaction.link",
"a"."interaction.mentions",
"a"."interaction.schema.version",
"a"."interaction.source",
"a"."interaction.tags",
"a"."interaction.title",
"a"."interaction.type",
"a"."interaction.subtype",
"a"."links.code",
"a"."links.created_at",
"a"."links.domain",
"a"."links.title",
"a"."links.url",
"a"."salience.content.sentiment",
"a"."twitter.created_at",
"a"."twitter.domains",
"a"."twitter.geo.latitude",
"a"."twitter.geo.longitude",
"a"."twitter.hashtags",
"a"."twitter.id",
"a"."twitter.in_reply_to_screen_name",
"a"."twitter.in_reply_to_status_id",
"a"."twitter.in_reply_to_user_id",
"a"."twitter.links",
"a"."twitter.media.display_url",
"a"."twitter.media.expanded_url",
"a"."twitter.media.id",
"a"."twitter.media.id_str",
"a"."twitter.media.media_url",
"a"."twitter.media.media_url_https",
"a"."twitter.media.source_status_id",
"a"."twitter.media.source_status_id_str",
"a"."twitter.media.type",
"a"."twitter.media.url",
"a"."twitter.mention_ids",
"a"."twitter.mentions",
"a"."twitter.place.attributes.locality",
"a"."twitter.place.attributes.region",
"a"."twitter.place.attributes.street_address",
"a"."twitter.place.country",
"a"."twitter.place.country_code",
"a"."twitter.place.full_name",
"a"."twitter.place.id",
"a"."twitter.place.name",
"a"."twitter.place.place_type",
"a"."twitter.place.url",
"a"."twitter.retweet.count",
"a"."twitter.retweet.created_at",
"a"."twitter.retweet.domains",
"a"."twitter.retweet.hashtags",
"a"."twitter.retweet.id",
"a"."twitter.retweet.links",
"a"."twitter.retweet.media.display_url",
"a"."twitter.retweet.media.expanded_url",
"a"."twitter.retweet.media.id",
"a"."twitter.retweet.media.id_str",
"a"."twitter.retweet.media.media_url",
"a"."twitter.retweet.media.media_url_https",
"a"."twitter.retweet.media.source_status_id",
"a"."twitter.retweet.media.source_status_id_str",
"a"."twitter.retweet.media.type",
"a"."twitter.retweet.media.url",
"a"."twitter.retweet.mention_ids",
"a"."twitter.retweet.mentions",
"a"."twitter.retweet.place.country",
"a"."twitter.retweet.place.country_code",
"a"."twitter.retweet.place.full_name",
"a"."twitter.retweet.place.id",
"a"."twitter.retweet.place.name",
"a"."twitter.retweet.place.place_type",
"a"."twitter.retweet.place.url",
"a"."twitter.retweet.source",
"a"."twitter.retweet.text",
"a"."twitter.retweet.user.created_at",
"a"."twitter.retweet.user.description",
"a"."twitter.retweet.favourites_count",
"a"."twitter.retweet.user.followers_count",
"a"."twitter.retweet.user.friends_count",
"a"."twitter.retweet.user.geo_enabled",
"a"."twitter.retweet.user.hash_id",
"a"."twitter.retweet.user.id",
"a"."twitter.retweet.user.id_str",
"a"."twitter.retweet.user.lang",
"a"."twitter.retweet.user.listed_count",
"a"."twitter.retweet.user.location",
"a"."twitter.retweet.user.name",
"a"."twitter.retweet.user.profile_image_url",
"a"."twitter.retweet.user.screen_name",
"a"."twitter.retweet.user.statuses_count",
"a"."twitter.retweet.user.time_zone",
"a"."twitter.retweet.user.url",
"a"."twitter.retweet.user.utc_offset",
"a"."twitter.retweet.user.verified",
"a"."twitter.retweeted.created_at",
"a"."twitter.retweeted.geo.latitude",
"a"."twitter.retweeted.geo.longitude",
"a"."twitter.retweeted.id",
"a"."twitter.retweeted.place.attributes.locality",
"a"."twitter.retweeted.place.attributes.region",
"a"."twitter.retweeted.place.attributes.street_address",
"a"."twitter.retweeted.place.country",
"a"."twitter.retweeted.place.country_code",
"a"."twitter.retweeted.place.full_name",
"a"."twitter.retweeted.place.id",
"a"."twitter.retweeted.place.name",
"a"."twitter.retweeted.place.place_type",
"a"."twitter.retweeted.place.url",
"a"."twitter.retweeted.source",
"a"."twitter.retweeted.user.created_at",
"a"."twitter.retweeted.user.description",
"a"."twitter.retweeted.favourites_count",
"a"."twitter.retweeted.user.followers_count",
"a"."twitter.retweeted.user.friends_count",
"a"."twitter.retweeted.user.geo_enabled",
"a"."twitter.retweeted.user.hash_id",
"a"."twitter.retweeted.user.id",
"a"."twitter.retweeted.user.id_str",
"a"."twitter.retweeted.user.lang",
"a"."twitter.retweeted.user.listed_count",
"a"."twitter.retweeted.user.location",
"a"."twitter.retweeted.user.name",
"a"."twitter.retweeted.user.profile_image_url",
"a"."twitter.retweeted.user.screen_name",
"a"."twitter.retweeted.user.statuses_count",
"a"."twitter.retweeted.user.time_zone",
"a"."twitter.retweeted.user.url",
"a"."twitter.retweeted.user.utc_offset",
"a"."twitter.retweeted.user.verified",
"a"."twitter.source",
"a"."twitter.status",
"a"."twitter.text",
"a"."twitter.user.created_at",
"a"."twitter.user.description",
"a"."twitter.user.favourites_count",
"a"."twitter.user.followers_count",
"a"."twitter.user.friends_count",
"a"."twitter.user.geo_enabled",
"a"."twitter.user.hash_id",
"a"."twitter.user.id",
"a"."twitter.user.id_str",
"a"."twitter.user.lang",
"a"."twitter.user.listed_count",
"a"."twitter.user.location",
"a"."twitter.user.name",
"a"."twitter.user.profile_image_url",
"a"."twitter.user.screen_name",
"a"."twitter.user.statuses_count",
"a"."twitter.user.time_zone",
"a"."twitter.user.url",
"a"."twitter.user.utc_offset",
"a"."twitter.user.verified",
CASE when "a"."interaction.tag_tree.BRAND" is NULL then ''
ELSE unnest("a"."interaction.tag_tree.BRAND")
END AS "interaction.tag_tree.BRAND"
from   
(SELECT 
	"demographic.gender",
	"facebook.application",
	"facebook.author.avatar",
	"facebook.author.id",
	"facebook.author.link",
	"facebook.author.name",
	"facebook.caption",
	"facebook.created_at",
	"facebook.description"	,
	"facebook.icon"	,
	"facebook.id",
	"facebook.likes.count",
	"facebook.likes.ids",
	"facebook.likes.names",
	"facebook.link"	,
	"facebook.message",
	"facebook.name"	,
	"facebook.og.app",
	"facebook.og.by",
	"facebook.og.length",
	"facebook.og.page",
	"facebook.og.photos",
	"facebook.picture",
	"facebook.place.id",
	"facebook.place.location.city",
	"facebook.place.location.country",
	"facebook.place.location.latitude",
	"facebook.place.location.longitude",
	"facebook.place.location.state",
	"facebook.place.location.street",
	"facebook.place.location.zip",
	"facebook.place.name",
	"facebook.source",
	"facebook.story",
	"facebook.story_tags.id",
	"facebook.story_tags.length",
	"facebook.story_tags.name",
	"facebook.story_tags.offset",
	"facebook.story_tags.type",
	"facebook.to.ids",
	"facebook.to.names",
	"facebook.type"	,
	"interaction.author.avatar",
	"interaction.author.contributions",
	"interaction.author.friends_count",
	"interaction.author.hash_id",
	"interaction.author.id",
	"interaction.author.link",
	"interaction.author.name",
	"interaction.author.talk",
	"interaction.author.url",
	"interaction.author.username",
	"interaction.content",
	"interaction.contenttype",
	"interaction.created_at",
	"interaction.geo.latitude",
	"interaction.geo.longitude",
	"interaction.hashtags",
	"interaction.id",
	"interaction.link",
	"interaction.mentions",
	"interaction.schema.version",
	"interaction.source",
	"interaction.tags",
	"interaction.title",
	"interaction.type",
	"interaction.subtype",
	"links.code",
	"links.created_at",
	"links.domain",
	"salience.content.sentiment",
	"twitter.created_at",
	"twitter.domains",
	"twitter.geo.latitude",
	"twitter.geo.longitude",
	"twitter.hashtags",
	"twitter.id",
	"twitter.in_reply_to_screen_name",
	"twitter.in_reply_to_status_id",
	"twitter.in_reply_to_user_id",
	"twitter.links",
	"twitter.media.display_url",
	"twitter.media.expanded_url",
	"twitter.media.id",
	"twitter.media.id_str",
	"twitter.media.media_url",
	"twitter.media.media_url_https",
	"twitter.media.source_status_id",
	"twitter.media.source_status_id_str",
	"twitter.media.type",
	"twitter.media.url",
	"twitter.mention_ids",
	"twitter.mentions",
	"twitter.place.attributes.locality",
	"twitter.place.attributes.region",
	"twitter.place.attributes.street_address",
	"twitter.place.country",
	"twitter.place.country_code",
	"twitter.place.full_name",
	"twitter.place.id",
	"twitter.place.name",
	"twitter.place.place_type",
	"twitter.place.url",
	"twitter.retweet.count",
	"twitter.retweet.created_at",
	"twitter.retweet.domains",
	"twitter.retweet.hashtags",
	"twitter.retweet.id",
	"twitter.retweet.links",
	"twitter.retweet.media.display_url",
	"twitter.retweet.media.expanded_url",
	"twitter.retweet.media.id",
	"twitter.retweet.media.id_str",
	"twitter.retweet.media.media_url",
	"twitter.retweet.media.media_url_https",
	"twitter.retweet.media.source_status_id",
	"twitter.retweet.media.source_status_id_str",
	"twitter.retweet.media.type",
	"twitter.retweet.media.url",
	"twitter.retweet.mention_ids",
	"twitter.retweet.mentions",
	"twitter.retweet.place.country",
	"twitter.retweet.place.country_code",
	"twitter.retweet.place.full_name",
	"twitter.retweet.place.id",
	"twitter.retweet.place.name",
	"twitter.retweet.place.place_type",
	"twitter.retweet.place.url",
	"twitter.retweet.source",
	"twitter.retweet.text",
	"twitter.retweet.user.created_at",
	"twitter.retweet.user.description",
	"twitter.retweet.favourites_count",
	"twitter.retweet.user.followers_count",
	"twitter.retweet.user.friends_count",
	"twitter.retweet.user.geo_enabled",
	"twitter.retweet.user.hash_id",
	"twitter.retweet.user.id",
	"twitter.retweet.user.id_str",
	"twitter.retweet.user.lang",
	"twitter.retweet.user.listed_count",
	"twitter.retweet.user.location",
	"twitter.retweet.user.name",
	"twitter.retweet.user.profile_image_url",
	"twitter.retweet.user.screen_name",
	"twitter.retweet.user.statuses_count",
	"twitter.retweet.user.time_zone",
	"twitter.retweet.user.url",
	"twitter.retweet.user.utc_offset",
	"twitter.retweet.user.verified",
	"twitter.retweeted.created_at",
	"twitter.retweeted.geo.latitude",
	"twitter.retweeted.geo.longitude",
	"twitter.retweeted.id",
	"twitter.retweeted.place.attributes.locality",
	"twitter.retweeted.place.attributes.region",
	"twitter.retweeted.place.attributes.street_address",
	"twitter.retweeted.place.country",
	"twitter.retweeted.place.country_code",
	"twitter.retweeted.place.full_name",
	"twitter.retweeted.place.id",
	"twitter.retweeted.place.name",
	"twitter.retweeted.place.place_type",
	"twitter.retweeted.place.url",
	"twitter.retweeted.source",
	"twitter.retweeted.user.created_at",
	"twitter.retweeted.user.description",
	"twitter.retweeted.favourites_count",
	"twitter.retweeted.user.followers_count",
	"twitter.retweeted.user.friends_count",
	"twitter.retweeted.user.geo_enabled",
	"twitter.retweeted.user.hash_id",
	"twitter.retweeted.user.id",
	"twitter.retweeted.user.id_str",
	"twitter.retweeted.user.lang",
	"twitter.retweeted.user.listed_count",
	"twitter.retweeted.user.location",
	"twitter.retweeted.user.name",
	"twitter.retweeted.user.profile_image_url",
	"twitter.retweeted.user.screen_name",
	"twitter.retweeted.user.statuses_count",
	"twitter.retweeted.user.time_zone",
	"twitter.retweeted.user.url",
	"twitter.retweeted.user.utc_offset",
	"twitter.retweeted.user.verified",
	"twitter.source",
	"twitter.status",
	"twitter.text",
	"twitter.user.created_at",
	"twitter.user.description",
	"twitter.user.favourites_count",
	"twitter.user.followers_count",
	"twitter.user.friends_count",
	"twitter.user.geo_enabled",
	"twitter.user.hash_id",
	"twitter.user.id",
	"twitter.user.id_str",
	"twitter.user.lang",
	"twitter.user.listed_count",
	"twitter.user.location",
	"twitter.user.name",
	"twitter.user.profile_image_url",
	"twitter.user.screen_name",
	"twitter.user.statuses_count",
	"twitter.user.time_zone",
	"twitter.user.url",
	"twitter.user.utc_offset",
	"twitter.user.verified",
	"interaction.tag_tree.BRAND",
	"links.title",
	CASE WHEN "links.url" is NULL then ''
	ELSE unnest("links.url")
	END AS "links.url"
	from explore_set
	where cast("links.url" as text) is NOT NULL
) a
;

